Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ParameterLists:
  Max: 10

AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 2.3
  NewCops: disable

